// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/94692a26d73bf75defb05e8da5f4d618ff27932d/blueimp-md5/index.d.ts
declare module 'blueimp-md5' {
// Type definitions for blueimp-md5 v2.7.0
// Project: https://github.com/blueimp/JavaScript-MD5
// Definitions by: Ray Martone <https://github.com/rmartone>, Mikael Kohlmyr <https://github.com/mkohlmyr>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

function md5(value: string, key?: string, raw?: boolean): string;
export = md5;
}
